on:
  release:
    types: [created]
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

name: test

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production
    
    steps:
    
    - name: Write value to Properties-file
      uses: christian-draeger/write-properties@1.1.0
      with:
        path: './src/test/resources/awsbrowser.properties'
        property: |
         'aws-access-key'
         'aws-secret-access-key'
        value: |
         'x'
         'second value'
